name: BusyBox Release Builder

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'BusyBox release tag to build'
        required: true
        type: string
      release:
        description: 'Create release?'
        required: true
        type: boolean
        default: true

env:
  MIRROR:  https://github.com/troglobit/misc/releases/download
  VERSION: 11-20211120

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    if: ${{ inputs.release }}
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: BusyBox Binaries v${{ inputs.tag }}
          body: |
            Release Notes
            =============
            Binaries for BusyBox v${{ inputs.tag }}.<br/>
            Please note, these builds are not sponsored by or affiliated with the BusyBox project.
          draft: false
          prerelease: false

  build:
    name: BusyBox v${{ inputs.tag }} ${{ matrix.cross }}cross
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cross: [ aarch64-linux-musl-,  arm-linux-musleabi-, armv5l-linux-musleabi-,  powerpc-linux-musl-, powerpc64-linux-musl-,  x86_64-linux-musl- ]
      fail-fast: false
    steps:
      - name: Check out Builder
        uses: actions/checkout@v2
      - name: Check out BusyBox
        uses: actions/checkout@v2
        with:
          repository: mirror/busybox
          ref: ${{ inputs.tag }}
          path: busybox
          clean: false
      - name: Install dependencies
        run: |
          ARCHIVE=${{ matrix.cross }}cross.tgz
          wget ${MIRROR}/${VERSION}/${ARCHIVE}
          tar xf ${ARCHIVE}
      - name: Build ${{ matrix.arch }}
        run: |
          export PATH=$(pwd)/${{ matrix.cross }}cross/bin:$PATH
          ./build-cross.sh ${{ matrix.cross }}
      - name: Uploading artifacts
        uses: pyTooling/Actions/releaser@main
        with:
          tag: ${{ inputs.tag }}
          rm: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: output/*
