name: BusyBox Release Builder

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'BusyBox tag to build'
        required: true
        type: string

jobs:
  build:
    name: BusyBox v${{ inputs.tag }} x86_64
    runs-on: ubuntu-latest
    container: muslcc/x86_64:x86_64-linux-musl
    steps:
      - name: Checkout BusyBox
        uses: actions/checkout@v2
        with:
          repository: mirror/busybox
          ref: ${{ inputs.tag }}
          path: busybox
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apk add make
      - name: Build
        run: |
          echo "Hello debugging ..."
          pwd
          ls ../
          ./build-docker.sh x86_64
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: BusyBox Binaries v${{ github.ref }}
          body: |
            Release Notes
            =============
            Binaries for BusyBox v${{ inputs.tag }}.<br/><br/>
            Please note, these builds are not sponsored by or affiliated with the BusyBox project.
          draft: false
          prerelease: false
      - name: Uploading artifacts
        uses: pyTooling/Actions/releaser@main
        with:
          tag: ${{ inputs.tag }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: output/*
