name: BusyBox Release Builder

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'BusyBox tag to build'
        required: true
        type: string

env:
  MIRROR:  https://github.com/troglobit/misc/releases/download
  VERSION: 11-20211120

jobs:
  build:
    name: BusyBox v${{ inputs.tag }} ${{ matrix.cross }}cross
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cross: [ aarch64-linux-musl-,  arm-linux-musleabi-, armv5l-linux-musleabi-,  powerpc-linux-musl-, powerpc64-linux-musl-,  x86_64-linux-musl- ]
      fail-fast: false
    steps:
      - name: Check out Builder
        uses: actions/checkout@v2
      - name: Check out BusyBox
        uses: actions/checkout@v2
        with:
          repository: mirror/busybox
          ref: ${{ inputs.tag }}
          path: busybox
          clean: false
      - name: Install dependencies
        run: |
          set -x
          TOOLCHAIN=${{ matrix.cross }}cross
          ARCHIVE=${TOOLCHAIN}.tgz
          wget ${MIRROR}/${VERSION}/${ARCHIVE}
          tar xf ${ARCHIVE}
          export PATH=$(pwd)/${TOOLCHAIN}/bin:$PATH
      - name: Build ${{ matrix.arch }}
        run: |
          ./build-cross.sh ${{ matrix.cross }}; cat busybox/BUILD.log
