name: BusyBox Release Builder

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'BusyBox tag to build'
        required: true
        type: string

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: BusyBox Binaries v${{ inputs.tag }}
          body: |
            Release Notes
            =============
            Binaries for BusyBox v${{ inputs.tag }}.<br/>
            Please note, these builds are not sponsored by or affiliated with the BusyBox project.
          draft: false
          prerelease: false
  build1:
    name: BusyBox v${{ inputs.tag }} ${{ matrix.arch }}
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [i686, x86_64, powerpc]
      fail-fast: false
    container: muslcc/x86_64:${{ matrix.arch }}-linux-musl
    steps:
      - name: Check out Builder
        uses: actions/checkout@v2
      - name: Check out BusyBox
        uses: actions/checkout@v2
        with:
          repository: mirror/busybox
          ref: ${{ inputs.tag }}
          path: busybox
          clean: false
      - name: Install dependencies
        run: |
          apk add make
      - name: Build ${{ matrix.arch }}
        run: |
          ./build-docker.sh ${{ matrix.arch }}
      - name: Uploading artifacts
        uses: pyTooling/Actions/releaser@main
        with:
          tag: ${{ inputs.tag }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: output/*
  build2:
    name: BusyBox v${{ inputs.tag }} ${{ matrix.arch }}
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv5l, armv7m]
      fail-fast: false
    container: muslcc/x86_64:${{ matrix.arch }}-linux-musleabi
    steps:
      - name: Check out Builder
        uses: actions/checkout@v2
      - name: Check out BusyBox
        uses: actions/checkout@v2
        with:
          repository: mirror/busybox
          ref: ${{ inputs.tag }}
          path: busybox
          clean: false
      - name: Install dependencies
        run: |
          apk add make
      - name: Build ${{ matrix.arch }}
        run: |
          ./build-docker.sh ${{ matrix.arch }}
      - name: Uploading artifacts
        uses: pyTooling/Actions/releaser@main
        with:
          tag: ${{ inputs.tag }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: output/*
